Repository chilleric/franchise-sys-backend, pull requests merged in 2023-01, with the labels that each got.

#37 35 implement bill repository
  src/main/java/com/chilleric/franchise_sys/dto/discount/DiscountResponse.java
  src/main/java/com/chilleric/franchise_sys/repository/common_entity/DraftDetail.java
  src/main/java/com/chilleric/franchise_sys/repository/common_entity/Timeline.java
  src/main/java/com/chilleric/franchise_sys/repository/common_enum/BillStatus.java
  src/main/java/com/chilleric/franchise_sys/repository/common_enum/PaymentMethod.java
  src/main/java/com/chilleric/franchise_sys/repository/common_enum/TypeObjectBill.java
  src/main/java/com/chilleric/franchise_sys/repository/crmRepository/bill/Bill.java
  src/main/java/com/chilleric/franchise_sys/repository/crmRepository/bill/BillRepository.java
  src/main/java/com/chilleric/franchise_sys/repository/crmRepository/bill/BillRepositoryImpl.java
Labels: documentation, enhancement

#31 implement Shifts service
  src/main/java/com/chilleric/franchise_sys/constant/DateTime.java
  src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java
  src/main/java/com/chilleric/franchise_sys/dto/shift/ShiftRequest.java
  src/main/java/com/chilleric/franchise_sys/dto/shift/ShiftResponse.java
  src/main/java/com/chilleric/franchise_sys/inventory/shift/ShiftInventory.java
  src/main/java/com/chilleric/franchise_sys/inventory/shift/ShiftInventoryImpl.java
  src/main/java/com/chilleric/franchise_sys/repository/informationRepository/shift/Shift.java
  src/main/java/com/chilleric/franchise_sys/repository/informationRepository/shift/ShiftRepository.java
  src/main/java/com/chilleric/franchise_sys/repository/informationRepository/shift/ShiftRepositoryImpl.java
  src/main/java/com/chilleric/franchise_sys/service/shift/ShiftService.java
  src/main/java/com/chilleric/franchise_sys/service/shift/ShiftServiceImpl.java
  src/main/java/com/chilleric/franchise_sys/utils/DateFormat.java
  src/main/java/com/chilleric/franchise_sys/utils/StringUtils.java
Labels: enhancement, good first issue

#62 61 bill service update completed workflow
  src/main/java/com/chilleric/franchise_sys/dto/bill/BillRequest.java
  src/main/java/com/chilleric/franchise_sys/dto/bill/BillResponse.java
  src/main/java/com/chilleric/franchise_sys/repository/crmRepository/bill/Bill.java
  src/main/java/com/chilleric/franchise_sys/service/bill/BillResponseServiceImpl.java
  src/main/java/com/chilleric/franchise_sys/service/bill/BillService.java
  src/main/java/com/chilleric/franchise_sys/service/bill/BillServiceImpl.java
Labels: enhancement

#64 update: add icon in Path
  src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java
  src/main/java/com/chilleric/franchise_sys/dto/path/PathRequest.java
  src/main/java/com/chilleric/franchise_sys/dto/path/PathResponse.java
  src/main/java/com/chilleric/franchise_sys/repository/systemRepository/path/Path.java
  src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
Labels: enhancement

#67 60 update hotel repository
  src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java
  src/main/java/com/chilleric/franchise_sys/dto/hotel/HotelRequest.java
  src/main/java/com/chilleric/franchise_sys/dto/hotel/HotelResponse.java
  src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionRequest.java
  src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionResponse.java
  src/main/java/com/chilleric/franchise_sys/repository/informationRepository/hotel/Hotel.java
  src/main/java/com/chilleric/franchise_sys/repository/systemRepository/permission/PermissionRepositoryImpl.java
  src/main/java/com/chilleric/franchise_sys/service/hotel/HotelServiceImpl.java
  src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
Labels: enhancement
